version: "3"

services:
  postgresql:
    image: postgres:16
    container_name: postgresql
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: cocoro
      POSTGRES_PASSWORD: Password
      POSTGRES_DB: MJDb
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    hostname: postgres
    restart: always
    user: root

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - 8000:80
    environment:
      PGADMIN_DEFAULT_EMAIL: your_email@example.com
      PGADMIN_DEFAULT_PASSWORD: your_password
    depends_on:
      - postgresql
    restart: always

volumes:
  db_data: {}